---
- name: Install mysql
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - mysql-server
  tags:
    - mysql

- name: Create a new database with name 'application'
  mysql_db:
    name: " {{database_name}}"
    state: present
    login_user: "{{database_user}}"
    login_password: "{{database_password}}"
  notify: restart mysql
  tags:
    - mysql
