---
- name: install mysql-server
  apt: pkg={{item}} state=latest
  with_items:
    - mysql-server
    - libmysqlclient-dev # required for Python MySQLB module
  tags:
    - mysql-server

- name: Install the Python MySQLB module (required for managing DB with ansible)
  pip:
    name: MySQL-python
  tags:
    - mysql-server

- name: create database
  mysql_db:
    name: "{{database_name}}"
    state: present
  tags:
    - mysql-server

- name: Create a new database with name 'application'
  mysql_db:
    name: " {{database_name}}"
    state: present
    login_user: "{{database_user}}"
    login_password: "{{database_password}}"
  notify: restart mysql
  tags:
    - mysql
- name: remove anonymous user for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
  tags:
    - mysql-server

- name: create user
  mysql_user:
    name: "{{database_user}}"
    password: "{{database_password}}"
    priv: '*.*:ALL'
    host: localhost
    state: present
  tags:
    - mysql-server
