---
- name: Install nginx
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - nginx

- name: Create nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags:
    - nginx
